export const commonCurrencies = [
    "Exalted Orb",
    "Exalted Shard",
    "Divine Orb",
    "Blessed Orb",
    "Ancient Orb",
    "Harbinger's Orb",
    "Orb of Annulment",
    "Annulment Shard",
    "Chaos Orb",
    "Orb of Regret",
    "Orb of Scouring",
    "Vaal Orb",
    "Regal Orb",
    "Orb of Alchemy",
    "Orb of Chance",
    "Orb of Binding",
    "Orb of Fusing",
    "Jeweller's Orb",
    "Chromatic Orb",
    "Orb of Alteration",
    "Silver Coin",
    "Gemcutter's Prism",
    "Cartographer's Chisel",
    "Engineer's Orb",
    "Orb of Horizons",
    "Glassblower's Bauble",
    "Mirror Shard",
    "Journeyman Cartographer's Sextant",
    "Apprentice Cartographer's Sextant",
    "Master Cartographer's Sextant"
];

export const breachCurrencies = [
    "Blessing of Chayula",
    "Blessing of Esh",
    "Blessing of Tul",
    "Blessing of Uul-Netol",
    "Blessing of Xoph",
    "Chayula's Breachstone",
    "Esh's Breachstone",
    "Tul's Breachstone",
    "Uul-Netol's Breachstone",
    "Xoph's Breachstone",
    "Splinter of Chayula",
    "Splinter of Esh",
    "Splinter of Tul",
    "Splinter of Uul-Netol",
    "Splinter of Xoph"
];

export const mapCurrencies = [
    "Mortal Grief",
    "Mortal Hope",
    "Mortal Ignorance",
    "Mortal Rage",
    "Offering to the Goddess",
    "Sacrifice at Dawn",
    "Sacrifice at Dusk",
    "Sacrifice at Midnight",
    "Sacrifice at Noon",
    "Eber's Key",
    "Inya's Key",
    "Volkuur's Key",
    "Yriel's Key",
    "Fragment of the Chimera",
    "Fragment of the Hydra",
    "Fragment of the Minotaur",
    "Fragment of the Phoenix",
    "Divine Vessel"
];

export const currencies = commonCurrencies.concat(breachCurrencies).concat(mapCurrencies);

export const thumbnails = {
    "Chaos Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollRare.png?scale=1&w=1&h=1",
    "Mirror Shard": "http://web.poecdn.com/image/Art/2DItems/Currency/MirrorShard.png?scale=1&w=1&h=1",
    "Blessing of Chayula": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachUpgraderChaos.png?scale=1&w=1&h=1",
    "Exalted Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyAddModToRare.png?scale=1&w=1&h=1",
    "Ancient Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/AncientOrb.png?scale=1&w=1&h=1",
    "Divine Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyModValues.png?scale=1&w=1&h=1",
    "Blessing of Uul-Netol": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachUpgraderPhysical.png?scale=1&w=1&h=1",
    "Master Cartographer's Sextant": "http://web.poecdn.com/image/Art/2DItems/Currency/AtlasRadiusRed.png?scale=1&w=1&h=1",
    "Harbinger's Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/HarbingerOrb.png?scale=1&w=1&h=1",
    "Exalted Shard": "http://web.poecdn.com/image/Art/2DItems/Currency/ExaltedShard.png?scale=1&w=1&h=1",
    "Blessing of Esh": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachUpgraderLightning.png?scale=1&w=1&h=1",
    "Journeyman Cartographer's Sextant": "http://web.poecdn.com/image/Art/2DItems/Currency/AtlasRadiusYellow.png?scale=1&w=1&h=1",
    "Orb of Annulment": "http://web.poecdn.com/image/Art/2DItems/Currency/AnnullOrb.png?scale=1&w=1&h=1",
    "Splinter of Chayula": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachShardChaos.png?scale=1&w=1&h=1",
    "Blessing of Xoph": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachUpgraderFire.png?scale=1&w=1&h=1",
    "Blessing of Tul": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachUpgraderCold.png?scale=1&w=1&h=1",
    "Apprentice Cartographer's Sextant": "http://web.poecdn.com/image/Art/2DItems/Currency/AtlasRadiusWhite.png?scale=1&w=1&h=1",
    "Orb of Regret": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyPassiveSkillRefund.png?scale=1&w=1&h=1",
    "Vaal Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyVaal.png?scale=1&w=1&h=1",
    "Regal Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyUpgradeMagicToRare.png?scale=1&w=1&h=1",
    "Gemcutter's Prism": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyGemQuality.png?scale=1&w=1&h=1",
    "Orb of Fusing": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollSocketLinks.png?scale=1&w=1&h=1",
    "Orb of Scouring": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyConvertToNormal.png?scale=1&w=1&h=1",
    "Blessed Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyImplicitMod.png?scale=1&w=1&h=1",
    "Cartographer's Chisel": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyMapQuality.png?scale=1&w=1&h=1",
    "Splinter of Xoph": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachShardFire.png?scale=1&w=1&h=1",
    "Orb of Horizons": "http://web.poecdn.com/image/Art/2DItems/Currency/HorizonOrb.png?scale=1&w=1&h=1",
    "Silver Coin": "http://web.poecdn.com/image/Art/2DItems/Currency/SilverObol.png?scale=1&w=1&h=1",
    "Orb of Alchemy": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyUpgradeToRare.png?scale=1&w=1&h=1",
    "Annulment Shard": "http://web.poecdn.com/image/Art/2DItems/Currency/AnnullShard.png?scale=1&w=1&h=1",
    "Orb of Binding": "http://web.poecdn.com/image/Art/2DItems/Currency/BindingOrb.png?scale=1&w=1&h=1",
    "Glassblower's Bauble": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyFlaskQuality.png?scale=1&w=1&h=1",
    "Orb of Chance": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyUpgradeRandomly.png?scale=1&w=1&h=1",
    "Jeweller's Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollSocketNumbers.png?scale=1&w=1&h=1",
    "Splinter of Uul-Netol": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachShardPhysical.png?scale=1&w=1&h=1",
    "Chromatic Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollSocketColours.png?scale=1&w=1&h=1",
    "Splinter of Tul": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachShardCold.png?scale=1&w=1&h=1",
    "Splinter of Esh": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachShardLightning.png?scale=1&w=1&h=1",
    "Orb of Alteration": "http://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollMagic.png?scale=1&w=1&h=1",
    "Engineer's Orb": "http://web.poecdn.com/image/Art/2DItems/Currency/EngineersOrb.png?scale=1&w=1&h=1",
    "Chayula's Breachstone": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachFragmentsChaos.png?scale=1&w=1&h=1",
    "Mortal Hope": "http://web.poecdn.com/image/Art/2DItems/Maps/UberVaal02.png?scale=1&w=1&h=1&v=db5b529a8425bd2b9fd7bee9fca2e0183",
    "Xoph's Breachstone": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachFragmentsFire.png?scale=1&w=1&h=1",
    "Volkuur's Key": "http://web.poecdn.com/image/Art/2DItems/Maps/PaleCourt04.png?scale=1&w=1&h=1&v=5c3afc6bad631a50f9fe5ccb570aeb363",
    "Mortal Ignorance": "http://web.poecdn.com/image/Art/2DItems/Maps/UberVaal03.png?scale=1&w=1&h=1&v=9fb218dad337a4627a59f74bfa2d6c863",
    "Inya's Key": "http://web.poecdn.com/image/Art/2DItems/Maps/PaleCourt03.png?scale=1&w=1&h=1&v=6e43b636847d46b560ef0518869a72943",
    "Uul-Netol's Breachstone": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachFragmentsPhysical.png?scale=1&w=1&h=1",
    "Esh's Breachstone": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachFragmentsLightning.png?scale=1&w=1&h=1",
    "Tul's Breachstone": "http://web.poecdn.com/image/Art/2DItems/Currency/Breach/BreachFragmentsCold.png?scale=1&w=1&h=1",
    "Fragment of the Chimera": "http://web.poecdn.com/image/Art/2DItems/Maps/AtlasMaps/FragmentChimera.png?scale=1&w=1&h=1&v=15bd6ba80e1853c22ae3acf40abf64283",
    "Yriel's Key": "http://web.poecdn.com/image/Art/2DItems/Maps/PaleCourt02.png?scale=1&w=1&h=1&v=757829336b7239c4b1e398c203f0cca03",
    "Offering to the Goddess": "http://web.poecdn.com/image/Art/2DItems/Maps/Labyrinth.png?scale=1&w=1&h=1&v=ef005aef5d2f9135d6922f4b1b912f783",
    "Fragment of the Phoenix": "http://web.poecdn.com/image/Art/2DItems/Maps/AtlasMaps/FragmentPhoenix.png?scale=1&w=1&h=1&v=8f76720ab06bb40a6d6f75730f92e4a73",
    "Mortal Rage": "http://web.poecdn.com/image/Art/2DItems/Maps/UberVaal01.png?scale=1&w=1&h=1&v=9336df5d7d0befd5963b71e7a68479ce3",
    "Fragment of the Minotaur": "http://web.poecdn.com/image/Art/2DItems/Maps/AtlasMaps/FragmentMinotaur.png?scale=1&w=1&h=1&v=e0e3f5e7daf32736d63fc3df1ba981223",
    "Fragment of the Hydra": "http://web.poecdn.com/image/Art/2DItems/Maps/AtlasMaps/FragmentHydra.png?scale=1&w=1&h=1&v=fd37e4be7672c0db8b549a1b16ad489d3",
    "Eber's Key": "http://web.poecdn.com/image/Art/2DItems/Maps/PaleCourt01.png?scale=1&w=1&h=1&v=044cbdae1e06e621585eaa627c2162db3",
    "Sacrifice at Midnight": "http://web.poecdn.com/image/Art/2DItems/Maps/Vaal01.png?scale=1&w=1&h=1&v=3b21ce0cd4c0b9e8cf5db6257daf831a3",
    "Divine Vessel": "http://web.poecdn.com/image/Art/2DItems/Maps/SinFlaskEmpty.png?scale=1&w=1&h=2",
    "Mortal Grief": "http://web.poecdn.com/image/Art/2DItems/Maps/UberVaal04.png?scale=1&w=1&h=1&v=735839ceae0fc45d15ec69555e9314133",
    "Sacrifice at Noon": "http://web.poecdn.com/image/Art/2DItems/Maps/Vaal03.png?scale=1&w=1&h=1&v=ba374d543316349b87de121039c3cc6f3",
    "Sacrifice at Dawn": "http://web.poecdn.com/image/Art/2DItems/Maps/Vaal02.png?scale=1&w=1&h=1&v=3ead6455599ec6c303f54ba98d6f8eb23",
    "Sacrifice at Dusk": "http://web.poecdn.com/image/Art/2DItems/Maps/Vaal04.png?scale=1&w=1&h=1"
};